### ISSUE TITLE
Please update prowlarr to latest version (1.12.2.4211 — Jan 18 2024)

### ISSUE THREAD

**Issue by moryoav** [hassio-addons/addon-prowlarr#5] opened 2024-02-05 18:42 UTC
Prowlarr was updated on January 18th. Please update this addon. Thank you.

**Comment by frenck** [comment] 2024-02-05 19:09
Hi there @moryoav 👋 

I'm closing this issue, as it is a request and not a bug.
That said, this is open source, feel free to open a PR to contribute such a bump 👍 

../Frenck

**Closed by frenck** 2024-02-05 19:09 UTC
